scorecard:
  output: text
  bundle: deploy/olm-catalog/argocd-operator
  plugins:
    - basic:
        cr-manifest:
          - examples/argocd-basic.yaml
          - examples/argocdexport-basic.yaml
    - olm:
        cr-manifest:
          - examples/argocd-basic.yaml
          - examples/argocdexport-basic.yaml
        csv-path: "deploy/olm-catalog/argocd-operator/0.0.16/argocd-operator.v0.0.16.clusterserviceversion.yaml"
